const fs = require('fs');
const path = require('path');

const dir = path.join(process.cwd(), 'public', 'media', 'forresterfields');
const exts = new Set(['.jpg','.jpeg','.png','.webp']);

let files = [];
try {
  files = fs.readdirSync(dir)
    .filter(f => exts.has(path.extname(f).toLowerCase()))
    .filter(f => {
      const low = f.toLowerCase();
      if (low.startsWith('.')) return false;          // hidden/trash
      if (low.startsWith('logo')) return false;       // exclude logo
      if (low.includes('mainbridge')) return false;   // exclude mainbridge
      return true;
    })
    .sort((a,b)=>a.localeCompare(b, undefined, {numeric:true}));
} catch {
  files = [];
}

const header = `// AUTO-GENERATED by scripts/pin-gallery.js
export type GalleryImage = string | { src: string; alt?: string };

export const GALLERY_FILES: GalleryImage[] = [
${files.map(f => `  "/media/forresterfields/${f}",`).join('\n')}
];
`;
fs.writeFileSync('src/lib/gallery.ts', header, 'utf8');
console.log('Pinned', files.length, 'images into src/lib/gallery.ts');
